<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="myrobot">
  <!-- Body properties -->
  <xacro:property name="body_radius" value="0.2" />
  <xacro:property name="body_length" value="0.6" />
  <xacro:property name="body_mass" value="2" />
  <xacro:property name="body_ixx" value="0.4" />
  <xacro:property name="body_iyy" value="0.4" />
  <xacro:property name="body_izz" value="0.2" />

  <!-- Thigh properties -->
  <xacro:property name="thigh_radius" value="0.1" />
  <xacro:property name="thigh_length" value="0.25" />
  <xacro:property name="thigh_mass" value="2" />
  <xacro:property name="thigh_ixx" value="0.02" />
  <xacro:property name="thigh_iyy" value="0.02" />
  <xacro:property name="thigh_izz" value="0.01" />

  <!-- Shin properties -->
  <xacro:property name="shin_radius" value="0.08" />
  <xacro:property name="shin_length" value="0.2" />
  <xacro:property name="shin_mass" value="1.5" />
  <xacro:property name="shin_ixx" value="0.015" />
  <xacro:property name="shin_iyy" value="0.015" />
  <xacro:property name="shin_izz" value="0.008" />

  <!-- Foot properties -->
  <xacro:property name="foot_length" value="0.3" />
  <xacro:property name="foot_width" value="0.2" />
  <xacro:property name="foot_height" value="0.05" />
  <xacro:property name="foot_mass" value="0.5" />
  <xacro:property name="foot_ixx" value="0.002" />
  <xacro:property name="foot_iyy" value="0.002" />
  <xacro:property name="foot_izz" value="0.001" />

  <xacro:property name="leg_offset" value="0.0" />

  <!-- Head properties -->
  <xacro:property name="head_radius" value="0.15" />
  <xacro:property name="head_mass" value="0.1" />
  <xacro:property name="head_ixx" value="0.01" />
  <xacro:property name="head_iyy" value="0.01" />
  <xacro:property name="head_izz" value="0.01" />

  <!-- IMU properties -->
  <xacro:property name="imu_length" value="0.03" />
  <xacro:property name="imu_width" value="0.05" />
  <xacro:property name="imu_height" value="0.05" />
  <xacro:property name="imu_mass" value="0.01" />
  <xacro:property name="imu_ixx" value="0.0001" />
  <xacro:property name="imu_iyy" value="0.0001" />
  <xacro:property name="imu_izz" value="0.0001" />
  
  <!-- Materials -->
  <material name="robot_material">
    <color rgba="0.37 0.09 0.09 1"/>
  </material>
   
  <!-- Body (main cylinder) -->
  <link name="base_link">
  <origin xyz="0 0 0"/>
    <visual>
      <origin xyz="0 0 ${body_length/2 + thigh_length}"/>
      <geometry>
        <cylinder length="${body_length}" radius="${body_radius}"/>
      </geometry>
      <material name="robot_material"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${body_length/2 + thigh_length}"/>
      <geometry>
        <cylinder length="${body_length}" radius="${body_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${body_mass}"/>
      <inertia ixx="${body_ixx}" ixy="0.0" ixz="0.0" iyy="${body_iyy}" iyz="0.0" izz="${body_izz}"/>
    </inertial>
  </link>

  <!-- IMU (simulated sensor, offset from body center) -->
  <link name="imu_link">
    <visual>
      <geometry>
        <box size="${imu_length} ${imu_width} ${imu_height}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="robot_material"/>
    </visual>
    <collision>
      <geometry>
        <box size="${imu_length} ${imu_width} ${imu_height}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="${imu_mass}"/>
      <inertia ixx="${imu_ixx}" ixy="0.0" ixz="0.0" iyy="${imu_iyy}" iyz="0.0" izz="${imu_izz}"/>
    </inertial>
  </link>

  <joint name="base_to_imu" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="${body_radius + imu_length/2} 0 ${imu_height/2 + thigh_length + body_length/3}" rpy="0 0 0"/>
  </joint>
  
  <!-- Head (sphere) -->
  <link name="head_link">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 ${head_radius + thigh_length}"/>
      <geometry>
        <sphere radius="${head_radius}"/>
      </geometry>
      <material name="robot_material"/>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 ${head_radius + thigh_length}"/>
      <geometry>
        <sphere radius="${head_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${head_mass}"/>
      <inertia ixx="${head_ixx}" ixy="0.0" ixz="0.0" iyy="${head_iyy}" iyz="0.0" izz="${head_izz}"/>
    </inertial>
  </link>

  <!-- Leg macro (creates left/right leg: thigh, shin, foot) -->
  <xacro:macro name="leg" params="prefix reflect">
    <!-- Thigh -->
    <link name="${prefix}_thigh_link">
      <visual>
        <geometry>
          <cylinder length="${thigh_length}" radius="${thigh_radius}"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 -${thigh_length/2}"/>
        <material name="robot_material"/>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${thigh_length}" radius="${thigh_radius}"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 -${thigh_length/2}"/>
      </collision>
      <inertial>
        <mass value="${thigh_mass}"/>
        <inertia ixx="${thigh_ixx}" ixy="0.0" ixz="0.0" iyy="${thigh_iyy}" iyz="0.0" izz="${thigh_izz}"/>
      </inertial>
    </link>

    <!-- Hip joint: base_link to thigh -->
    <joint name="base_to_${prefix}_thigh" type="revolute">
      <parent link="base_link"/>
      <child link="${prefix}_thigh_link"/>
      <origin xyz="0 ${(body_radius + thigh_radius + leg_offset) * reflect} ${thigh_length}"/>
      <axis xyz="0 1 0"/>
      <limit lower="-1.57" upper="1.57" effort="50" velocity="5"/>
    </joint>
  </xacro:macro>

  <!-- Instantiate right and left legs -->
  <xacro:leg prefix="right" reflect="-1" />
  <xacro:leg prefix="left" reflect="1" />
  
  <joint name="base_to_head" type="fixed">
    <parent link="base_link"/>
    <child link="head_link"/>
	<origin xyz="0 0 ${body_length}"/>
  </joint>
</robot>