<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="low_friction_plane_with_sections">
  <!-- Plane properties -->
  <xacro:property name="initial_section_length" value="1.0" />
  <xacro:property name="middle_section_length" value="8.0" />
  <xacro:property name="final_section_length" value="1.0" />
  <xacro:property name="plane_width" value="1.5" />
  <xacro:property name="plane_height" value="0.1" />
  <xacro:property name="section_mass" value="10000" />
  <xacro:property name="section_ixx" value="1000" />
  <xacro:property name="section_iyy" value="1000" />
  <xacro:property name="section_izz" value="1000" />
  <xacro:property name="pr_lateral_friction" value="0.8" />
  <xacro:property name="pr_rolling_friction" value="0.0" />
  <xacro:property name="pr_spinning_friction" value="0.0" />
  <xacro:property name="pba_lateral_friction" value="0.5" />
  <xacro:property name="pba_rolling_friction" value="0.8" />
  <xacro:property name="pba_spinning_friction" value="1.0" />

  <!-- Materials -->
  <material name="initial_section_material">
    <color rgba="0.8 0.8 0.8 1"/>
  </material>
  <material name="middle_section_material">
    <color rgba="0.5 0.8 1.0 1"/>
  </material>
  <material name="final_section_material">
    <color rgba="0.8 0.8 0.8 1"/>
  </material>
  
  <!-- Base Link - Initial Section -->
  <link name="initial_link">
    <contact>
      <lateral_friction value="${pr_lateral_friction}"/>
      <rolling_friction value="${pr_rolling_friction}"/>
      <spinning_friction value="${pr_spinning_friction}"/>
    </contact>
    <inertial>
      <origin xyz="0 0 -${plane_height/2}"/>
      <mass value="${section_mass}"/>
      <inertia ixx="${section_ixx}" ixy="0" ixz="0" iyy="${section_iyy}" iyz="0" izz="${section_izz}"/>
    </inertial>
    <visual>
      <origin xyz="0 0 -${plane_height/2}"/>
      <geometry>
        <box size="${initial_section_length} ${plane_width} ${plane_height}"/>
      </geometry>
      <material name="initial_section_material"/>
    </visual>
    <collision>
      <origin xyz="0 0 -${plane_height/2}"/>
      <geometry>
        <box size="${initial_section_length} ${plane_width} ${plane_height}"/>
      </geometry>
    </collision>
  </link>

  <!-- Middle Section -->
  <link name="middle_link">
    <contact>
      <lateral_friction value="${pba_lateral_friction}"/>
      <rolling_friction value="${pba_rolling_friction}"/>
      <spinning_friction value="${pba_spinning_friction}"/>
    </contact>
    <inertial>
      <origin xyz="0 0 -${plane_height/2}"/>
      <mass value="${section_mass}"/>
      <inertia ixx="${section_ixx}" ixy="0" ixz="0" iyy="${section_iyy}" iyz="0" izz="${section_izz}"/>
    </inertial>
    <visual>
      <origin xyz="0 0 -${plane_height/2}"/>
      <geometry>
        <box size="${middle_section_length} ${plane_width} ${plane_height}"/>
      </geometry>
      <material name="middle_section_material"/>
    </visual>
    <collision>
      <origin xyz="0 0 -${plane_height/2}"/>
      <geometry>
        <box size="${middle_section_length} ${plane_width} ${plane_height}"/>
      </geometry>
    </collision>
  </link>

  <!-- Final Section -->
  <link name="final_link">
    <contact>
      <lateral_friction value="${pr_lateral_friction}"/>
      <rolling_friction value="${pr_rolling_friction}"/>
      <spinning_friction value="${pr_spinning_friction}"/>
    </contact>
    <inertial>
      <origin xyz="0 0 -${plane_height/2}"/>
      <mass value="${section_mass}"/>
      <inertia ixx="${section_ixx}" ixy="0" ixz="0" iyy="${section_iyy}" iyz="0" izz="${section_izz}"/>
    </inertial>
    <visual>
      <origin xyz="0 0 -${plane_height/2}"/>
      <geometry>
        <box size="${final_section_length} ${plane_width} ${plane_height}"/>
      </geometry>
      <material name="final_section_material"/>
    </visual>
    <collision>
      <origin xyz="0 0 -${plane_height/2}"/>
      <geometry>
        <box size="${final_section_length} ${plane_width} ${plane_height}"/>
      </geometry>
    </collision>
  </link>

  <!-- Joints to connect all sections -->
  <joint name="initial_to_middle_joint" type="fixed">
    <parent link="initial_link"/>
    <child link="middle_link"/>
    <origin xyz="${initial_section_length/2 + middle_section_length/2} 0 0" rpy="0 0 0"/>
  </joint>

  <joint name="middle_to_final_joint" type="fixed">
    <parent link="middle_link"/>
    <child link="final_link"/>
    <origin xyz="${middle_section_length/2 + final_section_length/2} 0 0" rpy="0 0 0"/>
  </joint>

</robot>