<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="myrobot">
  <!-- Body properties -->
  <xacro:property name="body_radius" value="0.15" />
  <xacro:property name="body_length" value="0.3" />
  <xacro:property name="body_mass" value="5.0" />
  <xacro:property name="body_ixx" value="0.1" />
  <xacro:property name="body_iyy" value="0.1" />
  <xacro:property name="body_izz" value="0.05" />

  <!-- Hip properties -->
  <xacro:property name="hip_radius" value="0.05" />

  <!-- Thigh properties -->
  <xacro:property name="thigh_radius" value="0.04" />
  <xacro:property name="thigh_length" value="0.4" />
  <xacro:property name="thigh_mass" value="1.5" />
  <xacro:property name="thigh_ixx" value="0.02" />
  <xacro:property name="thigh_iyy" value="0.02" />
  <xacro:property name="thigh_izz" value="0.01" />

  <!-- Knee properties -->
  <xacro:property name="knee_radius" value="0.04" />

  <!-- Shin properties -->
  <xacro:property name="shin_radius" value="0.035" />
  <xacro:property name="shin_length" value="0.33" />
  <xacro:property name="shin_mass" value="1.0" />
  <xacro:property name="shin_ixx" value="0.015" />
  <xacro:property name="shin_iyy" value="0.015" />
  <xacro:property name="shin_izz" value="0.008" />

  <!-- Foot properties -->
  <xacro:property name="foot_length" value="0.2" />
  <xacro:property name="foot_width" value="0.1" />
  <xacro:property name="foot_height" value="0.03" />
  <xacro:property name="foot_offset_front" value="0.05" />
  <xacro:property name="foot_mass" value="0.3" />
  <xacro:property name="foot_ixx" value="0.001" />
  <xacro:property name="foot_iyy" value="0.001" />
  <xacro:property name="foot_izz" value="0.0005" />

  <!-- Head properties -->
  <xacro:property name="head_radius" value="0.1" />
  <xacro:property name="head_mass" value="0.2" />
  <xacro:property name="head_ixx" value="0.005" />
  <xacro:property name="head_iyy" value="0.005" />
  <xacro:property name="head_izz" value="0.005" />

  <!-- IMU properties -->
  <xacro:property name="imu_length" value="0.02" />
  <xacro:property name="imu_width" value="0.03" />
  <xacro:property name="imu_height" value="0.01" />
  <xacro:property name="imu_mass" value="0.01" />
  <xacro:property name="imu_ixx" value="0.00001" />
  <xacro:property name="imu_iyy" value="0.00001" />
  <xacro:property name="imu_izz" value="0.00001" />
  
  <!-- Materials -->
  <material name="robot_material_1">
    <color rgba="0.7 0.7 0.8 1"/>
  </material>
  <material name="robot_material_2">
    <color rgba="0.9 0.9 1.0 1"/>
  </material>

  <!-- altura total -->
  <xacro:property name="leg_total_length" value="${thigh_length + shin_length + foot_height}" />
  <!-- body_offset: body_length/2 desloca o posicao Z do centro do cilindro (corpo do robo) para a sua base inferior, assim nao fica metade do corpo enterrado no chao -->
  <!-- body_offset: leg_total_length da espaco para as pernas, para elas nao ficarem enterradas no chao -->
  <xacro:property name="body_offset" value="${body_length/2 + leg_total_length}" />
   
  <!-- Body (main cylinder) -->
  <link name="base_link">
    <origin xyz="0 0 0"/>
    <visual>
      <origin xyz="0 0 ${body_offset}"/>
      <geometry>
        <cylinder length="${body_length}" radius="${body_radius}"/>
      </geometry>
      <material name="robot_material_1"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${body_offset}"/>
      <geometry>
        <cylinder length="${body_length}" radius="${body_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${body_mass}"/>
      <inertia ixx="${body_ixx}" ixy="0.0" ixz="0.0" iyy="${body_iyy}" iyz="0.0" izz="${body_izz}"/>
    </inertial>
  </link>

  <!-- IMU (simulated sensor, offset from body center) -->
  <link name="imu_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${imu_length} ${imu_width} ${imu_height}"/>
      </geometry>
      <material name="robot_material_2"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${imu_length} ${imu_width} ${imu_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${imu_mass}"/>
      <inertia ixx="${imu_ixx}" ixy="0.0" ixz="0.0" iyy="${imu_iyy}" iyz="0.0" izz="${imu_izz}"/>
    </inertial>
  </link>

  <joint name="base_to_imu" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <!-- Z: Como o corpo principal e posicionado em 0 0 0, body_offset move a IMU para o centro do corpo -->
    <!-- Z: body_length/4 move a IMU um pouco para baixo, como se estivesse posicionado ela na cintura -->
    <origin xyz="${body_radius} 0 ${body_offset - body_length/4}" rpy="0 0 0"/>
  </joint>
  
  <!-- Head (sphere) -->
  <link name="head_link">
    <visual>
      <!-- Z: head_radius shifts the Z plane from the heads's center to its base -->
      <origin rpy="0 0 0" xyz="0 0 ${head_radius}"/>
      <geometry>
        <sphere radius="${head_radius}"/>
      </geometry>
      <material name="robot_material_2"/>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 ${head_radius}"/>
      <geometry>
        <sphere radius="${head_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${head_mass}"/>
      <inertia ixx="${head_ixx}" ixy="0.0" ixz="0.0" iyy="${head_iyy}" iyz="0.0" izz="${head_izz}"/>
    </inertial>
  </link>

  <!-- Head joint: body to head -->
  <joint name="base_to_head" type="fixed">
    <parent link="base_link"/>
    <child link="head_link"/>
    <!-- Z: Como o corpo principal e posicionado em 0 0 0, body_offset move a joint para o centro do corpo -->
    <!-- Z: body_length/2 move a joint para o topo do corpo -->
	  <origin xyz="0 0 ${body_offset + body_length/2}"/>
  </joint>

  <!-- Leg macro (creates left/right leg: thigh, shin, foot) -->
  <xacro:macro name="leg" params="prefix reflect">
    <!-- Thigh -->
    <link name="${prefix}_thigh_link">
      <visual>
        <!-- Z: thigh_length/2 desloca a posicao Z do centro do cilindro para a sua base inferior -->
        <!-- Z: hip_radius desloca a coxa para fora do quadril -->
        <origin rpy="0 0 0" xyz="0 0 ${-thigh_length/2 - hip_radius}"/>
        <geometry>
          <cylinder length="${thigh_length}" radius="${thigh_radius}"/>
        </geometry>
        <material name="robot_material_2"/>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 ${-thigh_length/2 - hip_radius}"/>
        <geometry>
          <cylinder length="${thigh_length}" radius="${thigh_radius}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="${thigh_mass}"/>
        <inertia ixx="${thigh_ixx}" ixy="0.0" ixz="0.0" iyy="${thigh_iyy}" iyz="0.0" izz="${thigh_izz}"/>
      </inertial>
    </link>

    <!-- Hip joint: base_link to thigh -->
    <joint name="base_to_${prefix}_thigh" type="revolute">
      <parent link="base_link"/>
      <child link="${prefix}_thigh_link"/>
      <!-- Z: Como o corpo principal e posicionado em 0 0 0, body_offset move a joint para o centro do corpo -->
      <!-- Z: body_length/2 move a joint para a base inferior do corpo -->
      <!-- Z: hip_radius faz a base inferior do quadrilcoincidir com a base inferior do corpo -->
      <!-- Y: body_radius posiciona a joint na borda do corpo -->
      <!-- Y: hip_radius tira o quadrilde dentro do corpo, caso contrario metade do quadrilficaria dentro do corpo -->
      <origin xyz="0 ${(body_radius + hip_radius) * reflect} ${body_offset - body_length/2 + hip_radius}"/>
      <axis xyz="0 1 0"/>
      <limit lower="-1.57" upper="1.57" effort="50" velocity="5"/>
    </joint>

    <!-- Shin -->
    <link name="${prefix}_shin_link">
      <visual>
        <!-- Z: shin_length/2 desloca a posicao Z do centro da coxa para a sua base inferior -->
        <!-- Z: knee_radius tira a coxa de dentro do quadril-->
        <origin rpy="0 0 0" xyz="0 0 ${-shin_length/2 - knee_radius}"/>
        <geometry>
          <cylinder length="${shin_length}" radius="${shin_radius}"/>
        </geometry>
        <material name="robot_material_1"/>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 ${-shin_length/2 - knee_radius}"/>
        <geometry>
          <cylinder length="${shin_length}" radius="${shin_radius}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="${shin_mass}"/>
        <inertia ixx="${shin_ixx}" ixy="0.0" ixz="0.0" iyy="${shin_iyy}" iyz="0.0" izz="${shin_izz}"/>
      </inertial>
    </link>

    <!-- Knee joint: thigh to shin -->
    <joint name="${prefix}_knee" type="revolute">
      <parent link="${prefix}_thigh_link"/>
      <child link="${prefix}_shin_link"/>
      <!-- Z: hip_radius + thigh_length faz o centro da cenela coincidir com a base inferior da coxa -->
      <!-- Z: knee_radius faz a base inferior da cenela coincidir com a base inferior da coxa -->
      <!-- Y: thigh_radius posiciona o centro da cenela na borda da coxa -->
      <!-- Y: knee_radius coloca a cenela para fora da coxa -->
      <origin xyz="0 ${(-thigh_radius + -knee_radius) * reflect} ${-hip_radius - thigh_length + knee_radius}"/>
      <axis xyz="0 1 0"/>
      <limit lower="0" upper="2.36" effort="40" velocity="5"/>
    </joint>

    <!-- Foot -->
    <link name="${prefix}_foot_link">
      <visual>
        <!-- Z: foot_height/2 desloca a posicao Z do centro do pe para o seu topo -->
        <!-- X: foot_offset_front desloca o pe um pouco para frente, para parecer um pe normal em que ele fica mais para frente do que para tras -->
        <origin rpy="0 0 0" xyz="${foot_offset_front} 0 ${-foot_height/2}"/>
        <geometry>
          <box size="${foot_length} ${foot_width} ${foot_height}"/>
        </geometry>
        <material name="robot_material_2"/>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 ${-foot_height/2}"/>
        <geometry>
          <box size="${foot_length} ${foot_width} ${foot_height}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="${foot_mass}"/>
        <inertia ixx="${foot_ixx}" ixy="0.0" ixz="0.0" iyy="${foot_iyy}" iyz="0.0" izz="${foot_izz}"/>
      </inertial>
    </link>

    <!-- Foot joint: shin to foot -->
    <joint name="${prefix}_foot_joint" type="fixed">
      <parent link="${prefix}_shin_link"/>
      <child link="${prefix}_foot_link"/>
      <!-- Z: knee_radius + shin_length faz o centro do pe coincidir com o centro da cenela -->
      <origin xyz="0 0 ${-knee_radius - shin_length}"/>
    </joint>

  </xacro:macro>

  <!-- Instantiate right and left legs -->
  <xacro:leg prefix="right" reflect="-1" />
  <xacro:leg prefix="left" reflect="1" />
  
</robot>