<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="myrobot">
  <!-- Body properties -->
  <xacro:property name="body_radius" value="0.15" />
  <xacro:property name="body_length" value="0.3" />
  <xacro:property name="body_mass" value="5.0" />
  <xacro:property name="body_ixx" value="0.1" />
  <xacro:property name="body_iyy" value="0.1" />
  <xacro:property name="body_izz" value="0.05" />

  <!-- Hip properties -->
  <xacro:property name="hip_radius" value="0.05" />

  <!-- Thigh properties -->
  <xacro:property name="thigh_radius" value="0.04" />
  <xacro:property name="thigh_length" value="0.4" />
  <xacro:property name="thigh_mass" value="1.5" />
  <xacro:property name="thigh_ixx" value="0.02" />
  <xacro:property name="thigh_iyy" value="0.02" />
  <xacro:property name="thigh_izz" value="0.01" />

  <!-- Knee properties -->
  <xacro:property name="knee_radius" value="0.04" />

  <!-- Shin properties -->
  <xacro:property name="shin_radius" value="0.035" />
  <xacro:property name="shin_length" value="0.33" />
  <xacro:property name="shin_mass" value="1.0" />
  <xacro:property name="shin_ixx" value="0.015" />
  <xacro:property name="shin_iyy" value="0.015" />
  <xacro:property name="shin_izz" value="0.008" />

  <!-- Foot properties -->
  <xacro:property name="foot_length" value="0.2" />
  <xacro:property name="foot_width" value="0.1" />
  <xacro:property name="foot_height" value="0.03" />
  <xacro:property name="foot_offset_front" value="0.05" />
  <xacro:property name="foot_mass" value="0.3" />
  <xacro:property name="foot_ixx" value="0.001" />
  <xacro:property name="foot_iyy" value="0.001" />
  <xacro:property name="foot_izz" value="0.0005" />

  <!-- Head properties -->
  <xacro:property name="head_radius" value="0.1" />
  <xacro:property name="head_mass" value="0.2" />
  <xacro:property name="head_ixx" value="0.005" />
  <xacro:property name="head_iyy" value="0.005" />
  <xacro:property name="head_izz" value="0.005" />

  <!-- IMU properties -->
  <xacro:property name="imu_length" value="0.02" />
  <xacro:property name="imu_width" value="0.03" />
  <xacro:property name="imu_height" value="0.01" />
  <xacro:property name="imu_mass" value="0.01" />
  <xacro:property name="imu_ixx" value="0.00001" />
  <xacro:property name="imu_iyy" value="0.00001" />
  <xacro:property name="imu_izz" value="0.00001" />
  
  <!-- Materials -->
  <material name="robot_material_1">
    <color rgba="0.7 0.7 0.8 1"/>
  </material>
  <material name="robot_material_2">
    <color rgba="0.9 0.9 1.0 1"/>
  </material>

  <!-- altura total -->
  <xacro:property name="total_height" value="${foot_height + shin_length + thigh_length + body_length + head_radius*2}" />
  <xacro:property name="base_z" value="${total_height/2}" />
   
  <!-- Body (main cylinder) -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${base_z - foot_height - shin_length - thigh_length - body_length/2}"/>
      <geometry>
        <cylinder length="${body_length}" radius="${body_radius}"/>
      </geometry>
      <material name="robot_material_1"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${base_z - foot_height - shin_length - thigh_length - body_length/2}"/>
      <geometry>
        <cylinder length="${body_length}" radius="${body_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${body_mass}"/>
      <inertia ixx="${body_ixx}" ixy="0.0" ixz="0.0" iyy="${body_iyy}" iyz="0.0" izz="${body_izz}"/>
    </inertial>
  </link>

  <!-- IMU (simulated sensor, offset from body center) -->
  <link name="imu_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${imu_length} ${imu_width} ${imu_height}"/>
      </geometry>
      <material name="robot_material_2"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${imu_length} ${imu_width} ${imu_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${imu_mass}"/>
      <inertia ixx="${imu_ixx}" ixy="0.0" ixz="0.0" iyy="${imu_iyy}" iyz="0.0" izz="${imu_izz}"/>
    </inertial>
  </link>

  <joint name="base_to_imu" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="${body_radius} 0 ${body_length/2 }" rpy="0 0 0"/>
  </joint>
  
  <!-- Head (sphere) -->
  <link name="head_link">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 ${head_radius}"/>
      <geometry>
        <sphere radius="${head_radius}"/>
      </geometry>
      <material name="robot_material_2"/>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 ${head_radius}"/>
      <geometry>
        <sphere radius="${head_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${head_mass}"/>
      <inertia ixx="${head_ixx}" ixy="0.0" ixz="0.0" iyy="${head_iyy}" iyz="0.0" izz="${head_izz}"/>
    </inertial>
  </link>

  <!-- Head joint: body to head -->
  <joint name="base_to_head" type="fixed">
    <parent link="base_link"/>
    <child link="head_link"/>
	  <origin xyz="0 0 ${body_length/2 + head_radius}"/>
  </joint>

  <!-- Leg macro (creates left/right leg: thigh, shin, foot) -->
  <xacro:macro name="leg" params="prefix reflect">
    <!-- Thigh -->
    <link name="${prefix}_thigh_link">
      <visual>
        <origin rpy="0 0 0" xyz="0 0 ${-thigh_length/2}"/>
        <geometry>
          <cylinder length="${thigh_length}" radius="${thigh_radius}"/>
        </geometry>
        <material name="robot_material_2"/>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 ${thigh_length/2}"/>
        <geometry>
          <cylinder length="${thigh_length}" radius="${thigh_radius}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="${thigh_mass}"/>
        <inertia ixx="${thigh_ixx}" ixy="0.0" ixz="0.0" iyy="${thigh_iyy}" iyz="0.0" izz="${thigh_izz}"/>
      </inertial>
    </link>

    <!-- Hip joint: base_link to thigh -->
    <joint name="base_to_${prefix}_thigh" type="revolute">
      <parent link="base_link"/>
      <child link="${prefix}_thigh_link"/>
      <origin xyz="0 ${body_radius * reflect} ${-body_length/2}"/>
      <axis xyz="0 1 0"/>
      <limit lower="-1.0" upper="1.0" effort="100" velocity="8"/>
    </joint>

    <!-- Shin -->
    <link name="${prefix}_shin_link">
      <visual>
        <origin rpy="0 0 0" xyz="0 0 ${-shin_length/2}"/>
        <geometry>
          <cylinder length="${shin_length}" radius="${shin_radius}"/>
        </geometry>
        <material name="robot_material_1"/>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 ${shin_length/2}"/>
        <geometry>
          <cylinder length="${shin_length}" radius="${shin_radius}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="${shin_mass}"/>
        <inertia ixx="${shin_ixx}" ixy="0.0" ixz="0.0" iyy="${shin_iyy}" iyz="0.0" izz="${shin_izz}"/>
      </inertial>
    </link>

    <!-- Knee joint: thigh to shin -->
    <joint name="${prefix}_knee" type="revolute">
      <parent link="${prefix}_thigh_link"/>
      <child link="${prefix}_shin_link"/>
      <origin xyz="0 0 ${-thigh_length/2}"/>
      <axis xyz="0 1 0"/>
      <limit lower="-0.5" upper="2.0" effort="60" velocity="8"/>
    </joint>

    <!-- Foot -->
    <link name="${prefix}_foot_link">
      <visual>
        <origin rpy="0 0 0" xyz="${foot_offset_front} 0 ${-foot_height/2}"/>
        <geometry>
          <box size="${foot_length} ${foot_width} ${foot_height}"/>
        </geometry>
        <material name="robot_material_2"/>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 ${-foot_height/2}"/>
        <geometry>
          <box size="${foot_length} ${foot_width} ${foot_height}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="${foot_mass}"/>
        <inertia ixx="${foot_ixx}" ixy="0.0" ixz="0.0" iyy="${foot_iyy}" iyz="0.0" izz="${foot_izz}"/>
      </inertial>
    </link>

    <!-- Foot joint: shin to foot -->
    <joint name="${prefix}_foot_joint" type="fixed">
      <parent link="${prefix}_shin_link"/>
      <child link="${prefix}_foot_link"/>
      <origin xyz="0 0 ${-knee_radius - shin_length}"/>
    </joint>

  </xacro:macro>

  <!-- Instantiate right and left legs -->
  <xacro:leg prefix="right" reflect="-1" />
  <xacro:leg prefix="left" reflect="1" />
  
</robot>